**TASK 1. Solving matrices**

*Exercise 1:*

In [1]:
# importing the NumPy library

import numpy as np

In [2]:
# declaration of matrix A

a = np.array(
 [[-1, 1,  2],
 [0, -1, -3],
  [4, -3, 2]]
 )
print(f"A = {a}")

A = [[-1  1  2]
 [ 0 -1 -3]
 [ 4 -3  2]]


In [3]:
# calculating the determinant of matrix A

det_a = round(np.linalg.det(a))
print(f"Determinant of base matrix A: {det_a}")

Determinant of base matrix A: 7


In [4]:
# inverse matrix to matrix A

a_back = np.linalg.inv(a)
print(f"Inverse matrix to matrix A: \n {a_back }")

Inverse matrix to matrix A: 
 [[-1.57142857 -1.14285714 -0.14285714]
 [-1.71428571 -1.42857143 -0.42857143]
 [ 0.57142857  0.14285714  0.14285714]]


In [5]:
# declaration of vector B

b = np.array([1, -4, 7])
print(b)

[ 1 -4  7]


In [6]:
# vector-column solutions:

print(f"Vector-column solutions: \n {a_back.dot(b)}")

Vector-column solutions: 
 [2. 1. 1.]


*Exercise 2:*

In [7]:
# declaration of matrix A

a = np.array(
 [[-3, -1,  0],
 [2, -2, 4],
  [5, -6, 2]]
 )
print(f"A = {a}")

A = [[-3 -1  0]
 [ 2 -2  4]
 [ 5 -6  2]]


In [8]:
# calculating the determinant of matrix A

det_a = round(np.linalg.det(a))
print(f"Determinant of base matrix A: {det_a}")

Determinant of base matrix A: -76


In [9]:
# inverse matrix to matrix A

a_back = np.linalg.inv(a)
print(f"Inverse matrix to matrix A: \n {a_back }")

Inverse matrix to matrix A: 
 [[-0.26315789 -0.02631579  0.05263158]
 [-0.21052632  0.07894737 -0.15789474]
 [ 0.02631579  0.30263158 -0.10526316]]


In [10]:
# declaration of vector B

b = np.array([4, 8, 13])
print(b)

[ 4  8 13]


In [11]:
# vector-column solutions:

print(f"Vector-column solutions: \n {a_back.dot(b)}")

Vector-column solutions: 
 [-0.57894737 -2.26315789  1.15789474]


**TASK 2: Solving a problem with a graphical description**


In [18]:
# declaration of matrix A
# x = tree
# y = apple
# z = banana

a = np.array(
 [[3, 0,  0],
 [0, 1, 2],
  [1, 2, 0]]
 )
print(f"A = {a}")

A = [[3 0 0]
 [0 1 2]
 [1 2 0]]


In [ ]:
# calculating the determinant of matrix A

det_a = round(np.linalg.det(a))
print(f"Determinant of base matrix A: {det_a}")

In [19]:
# declaration of vector B

b = np.array([60, 23, 30])
print(b)

[60 23 30]


In [20]:
# determining the vector X

x = np.linalg.solve(a, b)
print(f"X = {x}")

X = [20.  5.  9.]


In [21]:
# solving the task

res = x[0]+x[1]+x[2]
print(res)

34.0


**TASK 3. Solving a problem with a textual condition**


Data:

x - designers,

y - developers,

z - testers,

---






In [22]:
# declaration of matrix A
# x = designers
# y = developers
# z = testers

a = np.array(
 [[20, 3,  0],
 [8, 28, 4],
  [4, 12, 32]]
 )
print(f"A = {a}")

A = [[20  3  0]
 [ 8 28  4]
 [ 4 12 32]]


In [23]:
# calculating the determinant of matrix A

det_a = round(np.linalg.det(a))
print(f"Determinant of base matrix A: {det_a}")

Determinant of base matrix A: 16240


In [24]:
# declaration of vector B

b = np.array([800, 900, 600])
print(b)

[800 900 600]


In [25]:
# determining the vector X

x = np.linalg.solve(a, b)
print(f"X = {x}")

X = [36.89655172 20.68965517  6.37931034]


Solution (cost per hour):

designers = 36,90$

developers = 20,69$

testers = 6,80$

